use emojis instead of terminal color escapes

diff --git a/epm b/epm
--- a/epm
+++ b/epm
@@ -747,7 +747,7 @@ FLAGS:
     # Exits with status code 2 if the command failed.
     edo() {
         if ${VERBOSE}; then
-            printf "\\033[0;34m%s\\033[0m\\n" "$*" 1>&2
+            printf >&2 ' 🐞 %s\n' "$*"
         fi
         "$@" || exit 2
     }
@@ -758,7 +758,7 @@ FLAGS:
     # Print a blue debug message if verbosity is enabled.
     debug_message() {
         if ${VERBOSE}; then
-            (printf >&2 "\\033[0;34m%s\\033[0m\\n" "$1")
+            printf >&2 ' 🐞 %s\n' "$1"
         fi
     }
 
@@ -783,7 +783,7 @@ FLAGS:
     # @DESCRIPTION:
     # Print a green status message.
     status_message() {
-        printf >&2 "\\033[0;32m%s\\033[0m\\n" "$1"
+        printf >&2 ' \u2139\uFE0F %s\n' "$1"
     }
 
     # @FUNCTION: warning_message
@@ -791,7 +791,7 @@ FLAGS:
     # @DESCRIPTION:
     # Print a yellow warning message.
     warning_message() {
-        printf >&2 "\\033[1;33m%s\\033[0m\\n" "$1"
+        printf >&2 ' \u26A0\uFE0F  %s\n' "$1"
     }
 
     # @FUNCTION: red_message
@@ -799,7 +799,7 @@ FLAGS:
     # @DESCRIPTION:
     # Print a red message.
     red_message() {
-        printf >&2 "\\033[0;31m%s\\033[0m\\n" "$1"
+        printf >&2 ' ❗ %s\n' "$1"
     }
 
     # @FUNCTION: command_exists
@@ -831,7 +831,7 @@ FLAGS:
         unset com
 
         if [ -n "${_missing_commands}" ]; then
-            printf >&2 "%s" "${_missing_commands}"
+            printf >&2 '%s\n' "${_missing_commands}"
             unset _missing_commands
             return 1
         else
@@ -849,9 +849,9 @@ FLAGS:
         confirmation_msg=$1
 
         if [ -n "${confirmation_msg}" ]; then
-            printf >&2 "%s\\n(y/n and press Enter)\\n" "${confirmation_msg}"
+            printf >&2 '%s\n(y/n and press Enter)\n' "${confirmation_msg}"
         else
-            printf >&2 "Confirm action: (y/n and press Enter)\\n"
+            printf >&2 'Confirm action: (y/n and press Enter)\n'
         fi
         read -r answer </dev/tty
 
@@ -880,7 +880,7 @@ FLAGS:
             fi
             ;;
         -V | --version)
-            printf "%s\\n" "${VERSION}"
+            printf '%s\n' "${VERSION}"
             exit 0
             ;;
         -B | --base)
