all msg go to stderr instead of stdout

diff --git a/epm b/epm
--- a/epm
+++ b/epm
@@ -10,7 +10,7 @@
     # @VARIABLE: VERSION
     # @DESCRIPTION:
     # Version of this script.
-    VERSION=0.2.2
+    VERSION=0.2.3
 
     # Default base URL for short package names
     BASE_URL=${EPM_REPO_BASE:-"https://github.com/e-wrks"}
@@ -749,7 +749,7 @@ FLAGS:
     # Exits the shell script with status code 2
     # and prints the given message in red to STDERR, if any.
     die() {
-        (red_message >&2 "$1")
+        (red_message "$1")
         exit 2
     }
 
@@ -797,7 +797,7 @@ FLAGS:
     # @DESCRIPTION:
     # Print a green status message.
     status_message() {
-        printf "\\033[0;32m%s\\033[0m\\n" "$1"
+        printf >&2 "\\033[0;32m%s\\033[0m\\n" "$1"
     }
 
     # @FUNCTION: warning_message
@@ -805,7 +805,7 @@ FLAGS:
     # @DESCRIPTION:
     # Print a yellow warning message.
     warning_message() {
-        printf "\\033[1;33m%s\\033[0m\\n" "$1"
+        printf >&2 "\\033[1;33m%s\\033[0m\\n" "$1"
     }
 
     # @FUNCTION: red_message
@@ -813,7 +813,7 @@ FLAGS:
     # @DESCRIPTION:
     # Print a red message.
     red_message() {
-        printf "\\033[0;31m%s\\033[0m\\n" "$1"
+        printf >&2 "\\033[0;31m%s\\033[0m\\n" "$1"
     }
 
     # @FUNCTION: command_exists
@@ -845,7 +845,7 @@ FLAGS:
         unset com
 
         if [ -n "${_missing_commands}" ]; then
-            printf "%s" "${_missing_commands}"
+            printf >&2 "%s" "${_missing_commands}"
             unset _missing_commands
             return 1
         else
@@ -863,9 +863,9 @@ FLAGS:
         confirmation_msg=$1
 
         if [ -n "${confirmation_msg}" ]; then
-            printf "%s\\n(y/n and press Enter)\\n" "${confirmation_msg}"
+            printf >&2 "%s\\n(y/n and press Enter)\\n" "${confirmation_msg}"
         else
-            printf "Confirm action: (y/n and press Enter)\\n"
+            printf >&2 "Confirm action: (y/n and press Enter)\\n"
         fi
         read -r answer </dev/tty
 
