maintain symlinks under python_modules, use those for PYTHONPATH on exec, instead of dynamicly listing host.py from local packages

diff --git a/epm b/epm
--- a/epm
+++ b/epm
@@ -10,7 +10,7 @@
     # @VARIABLE: VERSION
     # @DESCRIPTION:
     # Version of this script.
-    VERSION=0.2.0
+    VERSION=0.2.1
 
     # Default base URL for short package names
     BASE_URL=${EPM_REPO_BASE:-"https://github.com/e-wrks"}
@@ -31,6 +31,7 @@
         (
             [ -w "${EPM_HOME}/edh_modules" ] || edo mkdir "${EPM_HOME}/edh_modules"
             [ -w "${EPM_HOME}/edh-universe/bin" ] || edo mkdir -p "${EPM_HOME}/edh-universe/bin"
+            [ -w "${EPM_HOME}/python_modules" ] || edo mkdir "${EPM_HOME}/python_modules"
         ) || die "Can NOT create EPM home artifacts in [${EPM_HOME}]"
     }
 
@@ -466,12 +467,26 @@ FLAGS:
         (
             edo pushd edh_modules >/dev/null
             for a in ../"${pkg_dir}"/edh_modules/*; do
+                # deal with empty dir without nullglob
+                [ ! -e "$a" ] && continue
                 b=$(basename "$a")
                 edo rm -rf "./$b" 2>/dev/null
                 edo ln -s "$a" "$b"
             done
             edo popd >/dev/null
         ) || die "Failed linking Edh module artifacts"
+
+        (
+            edo pushd python_modules >/dev/null
+            for a in ../"${pkg_dir}"/host.py/*; do
+                # deal with empty dir without nullglob
+                [ ! -e "$a" ] && continue
+                b=$(basename "$a")
+                edo rm -rf "./$b" 2>/dev/null
+                edo ln -s "$a" "$b"
+            done
+            edo popd >/dev/null
+        ) || die "Failed linking Python module artifacts"
 
         ${EPM_BUILD_HS} && ( (
             edo pushd "${pkg_dir}" >/dev/null
@@ -583,38 +598,23 @@ FLAGS:
             set -- cabal install --overwrite-policy=always --installdir=${EPM_HOME}/edh-universe/bin "$@"
         fi
 
-        collect_py_path() {
-            if [ ! -x "$1/edh-universe" ]; then
-                echo "${PYP}"
-                return 1 # reached an inaccessible epm home, stop here
-            fi
-            PYP=$(find "$1/edh-universe" -type d -name host.py | (
-                while read -r pyr; do
-                    if [ -n "${PYP}" ]; then
-                        PYP="${PYP}":"${pyr}"
-                    else
-                        PYP="${pyr}"
-                    fi
-                done
-                echo "${PYP}"
-            ))
-
-            parent_dir=$(dirname "$1")
-            if [ "${parent_dir}" == "$1" ]; then
-                echo "${PYP}"
-                return 0
-            fi
-
-            export PYP
-            collect_py_path "${parent_dir}"
-        }
-        PYP=$(PYP="" collect_py_path "${EPM_HOME}")
-        if [ -n "${PYP}" ]; then
-            if [ -n "${PYTHONPATH}" ]; then
-                export PYTHONPATH="${PYP}":"${PYTHONPATH}"
-            else
-                export PYTHONPATH="${PYP}"
-            fi
+        PYP=$(
+            PYP=""
+            IFS=: ps=(${EPM_PATH})
+            for p in ${ps[@]}; do
+                EPM_HOME=${p%%/edh-universe/bin}
+                if [ -n "${PYP}" ]; then
+                    PYP="${PYP}":"${EPM_HOME}"/python_modules
+                else
+                    PYP="${EPM_HOME}"/python_modules
+                fi
+            done
+            echo "${PYP}"
+        )
+        if [ -n "${PYTHONPATH}" ]; then
+            export PYTHONPATH="${PYP}":"${PYTHONPATH}"
+        else
+            export PYTHONPATH="${PYP}"
         fi
 
         export PATH="${EPM_PATH}":"${PATH}"
@@ -653,12 +653,33 @@ FLAGS:
 
                     edo pushd edh_modules >/dev/null
                     for a in ../"${pkg_dir}"/edh_modules/*; do
+                        # deal with empty dir without nullglob
+                        [ ! -e "$a" ] && continue
                         b=$(basename "$a")
                         edo rm -rf "./$b" 2>/dev/null
                         edo ln -s "$a" "$b"
                     done
                     edo popd >/dev/null
                 ) || die "Failed re-linking Edh module artifacts"
+
+                (
+                    find python_modules -type l | while read -r modu_root; do
+                        mr_path=$(readlink "${modu_root}")
+                        if [ "${mr_path#../${pkg_dir1}/}" != "${mr_path}" ]; then
+                            edo rm "${modu_root}" || die "Failed unlink ${modu_root}"
+                        fi
+                    done
+
+                    edo pushd python_modules >/dev/null
+                    for a in ../"${pkg_dir}"/host.py/*; do
+                        # deal with empty dir without nullglob
+                        [ ! -e "$a" ] && continue
+                        b=$(basename "$a")
+                        edo rm -rf "./$b" 2>/dev/null
+                        edo ln -s "$a" "$b"
+                    done
+                    edo popd >/dev/null
+                ) || die "Failed re-linking Python module artifacts"
 
                 ${EPM_BUILD_HS} && ( (
                     edo pushd "${pkg_dir}" >/dev/null
@@ -695,6 +716,12 @@ FLAGS:
                         if ask_for_confirmation "Remove it from [${EPM_HOME}] ?"; then
                             status_message "Removing ${pkg_dir} ..."
                             find edh_modules -type l | while read -r modu_root; do
+                                mr_path=$(readlink "${modu_root}")
+                                if [ "${mr_path#../${pkg_dir1}/}" != "${mr_path}" ]; then
+                                    edo rm "${modu_root}" || die "Failed unlink ${modu_root}"
+                                fi
+                            done
+                            find python_modules -type l | while read -r modu_root; do
                                 mr_path=$(readlink "${modu_root}")
                                 if [ "${mr_path#../${pkg_dir1}/}" != "${mr_path}" ]; then
                                     edo rm "${modu_root}" || die "Failed unlink ${modu_root}"
